version: '3'

services:
  osx-ventura:
    image: registry.cn-hangzhou.aliyuncs.com/shrimp-images/docker-osx:ventura
    devices:
      - /dev/kvm
    ports:
      - 50922:10022
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY:-:0.0}
      - GENERATE_UNIQUE=true
      - MASTER_PLIST_URL=https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist
    stdin_open: true
    tty: true
